version: '3.1'

services:
    test:
        build: 
            context: ../../
            dockerfile: docker/dev/Dockerfile
        command: python3 manage.py test todo.tests --noinput
        volumes:
            - build:/build
        environment: 
            DJANGO_SETTINGS_MODULE: todobackend.settings.test
            MYSQL_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            TEST_OUTPUT_DIR: /reports
    
    agent:
        image: reboot87/ansible
        environment:
            PROBE_HOST: "db"
            PROBE_PORT: "3306"
        command: ["probe.yaml"]
        depends_on:
            - db

    builder:
        build: 
            context: ../../
            dockerfile: docker/dev/Dockerfile
        volumes: 
            - build:/build            
        entrypoint: "entrypoint.sh"
        command: ["pip", "wheel", "-f /build", "."]

    db:
        image: mysql:5.7
        hostname: db
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: todobackend
            MYSQL_USER: todo
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: "%"
        volumes:
            - ./mysql57_db:/var/lib/mysql:delegated

volumes: 
    build: