version: '3.1'

services:
    test:
        build: 
            context: ../../../
            dockerfile: todobackend/Docker/dev/Dockerfile
        command: python3 manage.py test todo.tests
        environment: 
            DJANGO_SETTINGS_MODULE: todobackend.settings.test
            MYSQL_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            TEST_OUTPUT_DIR: /reports
        restart: on-failure
    
    agent:
        image: philm/ansible_playbook
        environment:
            PROBE_HOST: "db"
            PROBE_PORT: "3306"
        volumes:
            - ../../ansible:/ansible/playbooks
        command: ["probe.yaml"]
        depends_on:
            - db

    db:
        image: mysql:5.7
        hostname: db
        command: --default-authentication-plugin=mysql_native_password
        expose: 
            - "3306"
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: todobackend
            MYSQL_USER: todo
            MYSQL_PASSWORD: password
        volumes:
            - ~/mysql_db/:/var/lib/mysql:delegated